name: Deploy to Firebase Hosting Production
on: workflow_dispatch
env:
  ENVIRONMENT: production
  PROJECT: fp-cameroon
  CDN_ZONE: e12a5207c887608d69a76c72c0c22346
  DN: studio.fp-cameroon.com

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "cooking_firebase_config"
        run: make cook
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_FP_CAMEROON }}
          channelId: live
          projectId: ${{ env.PROJECT }}
      - name: purge_cdn
        run: make purge
